provider: local 
ClusterLoader:
  cleanup: false
  projects:
  - num: 700
    basename: serverless-other-ns
    tuning: default
    ifexists: delete
    templates:
    - num: 1
      file: ./content/configmap-template.json
  - num: 300
    basename: serverless-ksvc-ns
    tuning: default
    ifexists: delete
    templates:
    - num: 10
      file: ./content/serverless-ksvc-ns.json
  tuningsets: 
  - name: default
    templates:
      stepping: 
        stepsize: 10
        pause: 0 s
      rate_limit: 
        delay: 0 ms
